openapi: 3.1.0
info:
  title: MicServ1-SOC - Identity Service
  description: Microservicio REST para la Gestión de Identidad y Clientes. 
    Permite el registro e inicio de sesión de usuarios, define roles (Registrado/Invitado) 
    y emite tokens seguros (JWT) para acceder al resto de los microservicios.
  version: 1.1.0
tags:
  - name: Health Check
    description: Estado del servicio y conexiones
  - name: Autenticación
    description: Registro, Login y gestión de tokens
  - name: Gestión de Usuarios
    description: Perfil y administración de usuarios
  - name: Usuarios Invitados
    description: Funcionalidad para usuarios no registrados

paths:
  /:
    get:
      tags:
        - Health Check
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}

  /health:
    get:
      tags:
        - Health Check
      summary: Health Check
      operationId: health_check_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}

  /db/connection/health:
    get:
      tags:
        - Health Check
      summary: Db Health Check
      operationId: db_health_check_db_connection_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}

  /api/auth/register:
    post:
      tags:
        - Autenticación
      summary: Registro de nuevos usuarios
      description: Registra un nuevo usuario en la plataforma.
      operationId: register_route_api_auth_register_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              Petición Válida:
                summary: Ejemplo de un registro exitoso
                value:
                  name: "Juan"
                  lastName: "Pérez"
                  lastName2: "García"
                  email: "juan.perez@ejemplo.com"
                  password: "SecurePass123!"
                  cellPhone: "+525512345678"
                  cfToken: "token_captcha"
      responses:
        '201':
          description: Usuario registrado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  mensaje:
                    type: string
              examples:
                Éxito:
                  value:
                    id: "usr_12345abc"
                    name: "Juan"
                    email: "juan.perez@ejemplo.com"
                    mensaje: "Usuario registrado exitosamente"
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'
        '409':
          description: Conflicto - El correo ya existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorConflict'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

  /api/auth/login:
    post:
      tags:
        - Autenticación
      summary: Inicio de sesión de usuarios
      description: Autentica al usuario mediante credenciales y devuelve un token de acceso (JWT) y un token de refresco.
      operationId: login_route_api_auth_login_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
            examples:
              Credenciales Válidas:
                value:
                  email: "juan.perez@ejemplo.com"
                  password: "SecurePass123!"
                  cfToken: "token_captcha"
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: Token JWT para acceso a recursos protegidos.
                  refreshToken:
                    type: string
                    description: Token para obtener un nuevo accessToken.
                  expiresIn:
                    type: integer
                  user:
                    type: object
                    properties:
                      id: { type: string }
                      name: { type: string }
                      role: { type: string }
              examples:
                Éxito:
                  value:
                    accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    refreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    expiresIn: 3600
                    user:
                      id: "usr_12345abc"
                      name: "Juan"
                      role: "CLIENTE"
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUnauthorized'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

  /api/auth/logout:
    post:
      tags:
        - Autenticación
      summary: Cierre de sesión
      description: Invalida el token de refresco del usuario.
      operationId: logout_route_api_auth_logout_post
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Sesión cerrada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUnauthorized'

  /api/auth/refresh-token:
    post:
      tags:
        - Autenticación
      summary: Renovación de token JWT
      operationId: refresh_token_route_api_auth_refresh_token_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Token renovado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken: { type: string }
                  refreshToken: { type: string }
        '401':
          description: Refresh token expirado o no autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUnauthorized'

  /api/auth/forgot-password:
    post:
      tags:
        - Autenticación
      summary: Recuperación de contraseña
      operationId: forgot_password_route_api_auth_forgot_password_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        '200':
          description: Solicitud procesada (Email enviado si existe)
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje: { type: string }
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

  /api/auth/reset-password:
    post:
      tags:
        - Autenticación
      summary: Reset Password Route
      operationId: reset_password_route_api_auth_reset_password_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
        required: true
      responses:
        '200':
          description: Contraseña actualizada correctamente
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

  /api/users/profile:
    get:
      tags:
        - Gestión de Usuarios
      summary: Obtener perfil del usuario
      description: Retorna la información detallada del usuario actual.
      operationId: read_profile_api_users_profile_get
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Perfil encontrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
              examples:
                Perfil Actual:
                  value:
                    name: "Brayhan"
                    lastName: "Hoyos"
                    lasrName: "Hernandez"
                    email: "brayhan26@gmail.com"
                    cellPhone: "tel:+52-222-333-4445"
        '401':
          description: No autorizado
    put:
      tags:
        - Gestión de Usuarios
      summary: Actualizar perfil
      operationId: update_profile_api_users_profile_put
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
        required: true
      responses:
        '200':
          description: Perfil actualizado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
        - Gestión de Usuarios
      summary: Eliminar cuenta
      operationId: delete_profile_api_users_profile_delete
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cuenta eliminada exitosamente

  /api/users/{id}:
    get:
      tags:
        - Gestión de Usuarios
      summary: Obtener usuario por ID (Admin)
      operationId: read_user_by_id_api_users__id__get
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            title: Id
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '404':
          description: Usuario no encontrado
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

  /api/guest/session:
    post:
      tags:
        - Usuarios Invitados
      summary: Crear sesión de invitado
      operationId: create_session_api_guest_session_post
      responses:
        '201':
          description: Sesión creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GuestSession'

  /api/guest/features:
    get:
      tags:
        - Usuarios Invitados
      summary: Funcionalidades disponibles para invitados
      operationId: read_features_api_guest_features_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GuestFeatures'
              examples:
                Lista de Features:
                  value:
                    features: ["Ver catálogo", "Buscar productos", "Ver detalles"]

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorBadRequest:
      type: object
      properties:
        statusCode: { type: integer, example: 400 }
        message: { type: string, example: "Datos de entrada inválidos" }
        errors:
          type: array
          items:
            type: object
            properties:
              field: { type: string }
              message: { type: string }

    ErrorUnauthorized:
      type: object
      properties:
        statusCode: { type: integer, example: 401 }
        message: { type: string, example: "No autorizado" }

    ErrorConflict:
      type: object
      properties:
        statusCode: { type: integer, example: 409 }
        message: { type: string, example: "El recurso ya existe" }

    ErrorNotFound:
      type: object
      properties:
        statusCode: { type: integer, example: 404 }
        message: { type: string, example: "Recurso no encontrado" }

    ForgotPasswordRequest:
      properties:
        email:
          type: string
          format: email
          title: Email
      type: object
      required:
        - email
      title: ForgotPasswordRequest

    ResetPasswordRequest:
      properties:
        token:
          type: string
          title: Token
        new_password:
          type: string
          title: New Password
      type: object
      required:
        - token
        - new_password
      title: ResetPasswordRequest

    User:
      properties:
        name:
          type: string
          title: Name
          description: Nombre(s) del usuario
        lastName:
          type: string
          title: Lastname
          description: Apellido paterno
        lastName2:
          anyOf:
            - type: string
            - type: 'null'
          title: Lastname2
          description: Apellido materno (opcional)
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          title: Password
        cellPhone:
          type: string
          format: phone
          title: Cellphone
        cfToken:
          type: string
          title: Cftoken
          description: Token de verificación (Captcha)
      type: object
      required:
        - name
        - lastName
        - email
        - password
        - cellPhone
        - cfToken
      title: User

    UserLogin:
      properties:
        email:
          type: string
          format: email
          title: Email
        password:
          type: string
          title: Password
        cfToken:
          type: string
          title: Cftoken
      type: object
      required:
        - email
        - password
        - cfToken
      title: UserLogin

    UserUpdate:
      properties:
        name:
          anyOf:
            - type: string
            - type: 'null'
          title: Name
        lastName:
          anyOf:
            - type: string
            - type: 'null'
          title: Lastname
        lastName2:
          anyOf:
            - type: string
            - type: 'null'
          title: Lastname2
        email:
          anyOf:
            - type: string
              format: email
            - type: 'null'
          title: Email
        password:
          anyOf:
            - type: string
            - type: 'null'
          title: Password
        cellPhone:
          anyOf:
            - type: string
              format: phone
            - type: 'null'
          title: Cellphone
      type: object
      title: UserUpdate

    UserProfile:
      type: object
      properties:
        id:
          type: integer
          example: 540
        name:
          type: string
          example: "Brayhan"
        lastName:
          type: string
          example: "Hoyos"
        lastName2:
          type: string
          example: "Hernandez"
        email:
          type: string
          format: email
          example: "brayhan26@gmail.com"

    GuestFeatures:
      properties:
        features:
          items:
            type: string
          type: array
          title: Features
          description: Lista de permisos o funcionalidades para el invitado
      type: object
      required:
        - features
      title: GuestFeatures

    GuestSession:
      properties:
        guestId:
          type: string
          title: Guestid
        sessionToken:
          type: string
          title: Sessiontoken
        expiresIn:
          type: integer
          title: Expiresin
      type: object
      required:
        - guestId
        - sessionToken
        - expiresIn
      title: GuestSession

    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError

    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError